### ISSUE TITLE
No provider for NgsgSortService

### ISSUE THREAD

**Issue by PavelZgurski** [kreuzerk/ng-sortgrid#33]
Hi. I think that it is the same issues as https://github.com/kreuzerk/ng-sortgrid/issues/30 but it is already closed. When I use ng-sortgrid from demo folder from github not from npm or yarn - it works well

`NullInjectorError: StaticInjectorError(AppModule)[NgsgItemDirective -> NgsgSortService]: 
  StaticInjectorError(Platform: core)[NgsgItemDirective -> NgsgSortService]: 
    NullInjectorError: No provider for NgsgSortService!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (http://localhost:4200/vendor.js:76429:25)
    at resolveToken (http://localhost:4200/vendor.js:87622:24)
    at tryResolveToken (http://localhost:4200/vendor.js:87566:16)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:87468:20)
    at resolveToken (http://localhost:4200/vendor.js:87622:24)
    at tryResolveToken (http://localhost:4200/vendor.js:87566:16)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (http://localhost:4200/vendor.js:87468:20)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:95938:29)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (http://localhost:4200/vendor.js:96609:16)
    at resolveNgModuleDep (http://localhost:4200/vendor.js:95938:29)`

**Comment by kreuzerk** [comment]
I tried it last time with a version I installed from npm. I guess it could be a problem with the Angular version. Which Angular version do you use?

**Comment by PavelZgurski** [comment]
> I tried it last time with a version I installed from npm. I guess it could be a problem with the Angular version. Which Angular version do you use?

"@angular/core": "8.2.14"

**Comment by kreuzerk** [comment]
I think that's the Issue. The latest version of ng-sortgrid is made for Angular 9. With Angular 9 everything works. Version 1.3.3 of sortgrid should also work for Angular 8. Will try to figure out if there's a fix for this.

**Comment by PavelZgurski** [comment]
@kreuzerk 1.3.3 works fine for me on Angular 8. Thanks.
